# Color Picker
# Code by Rahul.R

from tkinter import *
from time import sleep

obj = Tk()
obj.geometry('572x430')
obj.title('Color Picker')
obj.configure(bg='black')

count = 22


def click():
    counter(count)


def change(c):
    if c == 1:
        color8()
        obj.update()
        sleep(0.5)
        counter(c)
    elif c == 2:
        color12()
        obj.update()
        sleep(0.5)
        counter(c)
    elif c == 3:
        color4()

        obj.update()
        sleep(0.5)
        counter(c)
    elif c == 4:
        color6()
        obj.update()
        sleep(0.5)
        counter(c)
    elif c == 5:
        color15()
        obj.update()
        sleep(0.5)
        counter(c)
    elif c == 6:
        color17()
        obj.update()
        sleep(0.5)
        counter(c)
    elif c == 7:
        color7()
        obj.update()
        sleep(0.5)
        counter(c)
    elif c == 8:
        color19()
        obj.update()
        sleep(0.5)
        counter(c)
    elif c == 9:
        color3()
        obj.update()
        sleep(0.5)
        counter(c)
    elif c == 10:
        color5()
        obj.update()
        sleep(0.5)
        counter(c)
    elif c == 11:
        color1()
        obj.update()
        sleep(0.5)
        counter(c)
    elif c == 12:
        color21()
        obj.update()
        sleep(0.5)
        counter(c)
    elif c == 13:
        color13()
        obj.update()
        sleep(0.5)
        counter(c)
    elif c == 14:
        color9()
        obj.update()
        sleep(0.5)
        counter(c)
    elif c == 15:
        color16()
        obj.update()
        sleep(0.5)
        counter(c)
    elif c == 16:
        color18()
        obj.update()
        sleep(0.5)
        counter(c)
    elif c == 17:
        color2()
        obj.update()
        sleep(0.5)
        counter(c)
    elif c == 18:
        color11()
        obj.update()
        sleep(0.5)
        counter(c)
    elif c == 19:
        color20()
        obj.update()
        sleep(0.5)
        counter(c)
    elif c == 20:
        color14()
        obj.update()
        sleep(0.5)
        counter(c)
    elif c == 21:
        color10()
        obj.update()
        sleep(0.5)
        counter(c)
    elif c == 0:
        color10()
        obj.update()
        sleep(0.5)
        counter(c)


def counter(cou):
    if cou > 0:
        cou -= 1
        change(cou)
    elif cou == 0:
        cou = 21
        change(cou)


def color1():
    plate1 = Canvas(obj, bg='Red', height=70, width=70)
    plate1.create_text(38, 35, text="RED", fill="black", font='Helvetica 10 bold')
    plate1.grid(row=3, column=1)
    plate2 = Canvas(obj, bg='black', height=70, width=70)
    plate2.grid(row=3, column=2)
    plate3 = Canvas(obj, bg='black', height=70, width=70)
    plate3.grid(row=3, column=3)
    plate4 = Canvas(obj, bg='black', height=70, width=70)
    plate4.grid(row=3, column=4)
    plate5 = Canvas(obj, bg='black', height=70, width=70)
    plate5.grid(row=3, column=5)
    plate6 = Canvas(obj, bg='black', height=70, width=70)
    plate6.grid(row=3, column=6)
    plate7 = Canvas(obj, bg='black', height=70, width=70)
    plate7.grid(row=3, column=7)
    plate8 = Canvas(obj, bg='black', height=70, width=70)
    plate8.grid(row=5, column=1)
    plate9 = Canvas(obj, bg='black', height=70, width=70)
    plate9.grid(row=5, column=2)
    plate10 = Canvas(obj, bg='black', height=70, width=70)
    plate10.grid(row=5, column=3)
    plate11 = Canvas(obj, bg='black', height=70, width=70)
    plate11.grid(row=5, column=4)
    plate12 = Canvas(obj, bg='black', height=70, width=70)
    plate12.grid(row=5, column=5)
    plate13 = Canvas(obj, bg='black', height=70, width=70)
    plate13.grid(row=5, column=6)
    plate14 = Canvas(obj, bg='black', height=70, width=70)
    plate14.grid(row=5, column=7)
    plate15 = Canvas(obj, bg='black', height=70, width=70)
    plate15.grid(row=7, column=1)
    plate16 = Canvas(obj, bg='black', height=70, width=70)
    plate16.grid(row=7, column=2)
    plate17 = Canvas(obj, bg='black', height=70, width=70)
    plate17.grid(row=7, column=3)
    plate18 = Canvas(obj, bg='black', height=70, width=70)
    plate18.grid(row=7, column=4)
    plate19 = Canvas(obj, bg='black', height=70, width=70)
    plate19.grid(row=7, column=5)
    plate20 = Canvas(obj, bg='black', height=70, width=70)
    plate20.grid(row=7, column=6)
    plate21 = Canvas(obj, bg='black', height=70, width=70)
    plate21.grid(row=7, column=7)


def color2():
    plate1 = Canvas(obj, bg='black', height=70, width=70)
    plate1.grid(row=3, column=1)
    plate2 = Canvas(obj, bg='blue', height=70, width=70)
    plate2.create_text(38, 35, text="BLUE", fill="black", font='Helvetica 10 bold')
    plate2.grid(row=3, column=2)
    plate3 = Canvas(obj, bg='black', height=70, width=70)
    plate3.grid(row=3, column=3)
    plate4 = Canvas(obj, bg='black', height=70, width=70)
    plate4.grid(row=3, column=4)
    plate5 = Canvas(obj, bg='black', height=70, width=70)
    plate5.grid(row=3, column=5)
    plate6 = Canvas(obj, bg='black', height=70, width=70)
    plate6.grid(row=3, column=6)
    plate7 = Canvas(obj, bg='black', height=70, width=70)
    plate7.grid(row=3, column=7)
    plate8 = Canvas(obj, bg='black', height=70, width=70)
    plate8.grid(row=5, column=1)
    plate9 = Canvas(obj, bg='black', height=70, width=70)
    plate9.grid(row=5, column=2)
    plate10 = Canvas(obj, bg='black', height=70, width=70)
    plate10.grid(row=5, column=3)
    plate11 = Canvas(obj, bg='black', height=70, width=70)
    plate11.grid(row=5, column=4)
    plate12 = Canvas(obj, bg='black', height=70, width=70)
    plate12.grid(row=5, column=5)
    plate13 = Canvas(obj, bg='black', height=70, width=70)
    plate13.grid(row=5, column=6)
    plate14 = Canvas(obj, bg='black', height=70, width=70)
    plate14.grid(row=5, column=7)
    plate15 = Canvas(obj, bg='black', height=70, width=70)
    plate15.grid(row=7, column=1)
    plate16 = Canvas(obj, bg='black', height=70, width=70)
    plate16.grid(row=7, column=2)
    plate17 = Canvas(obj, bg='black', height=70, width=70)
    plate17.grid(row=7, column=3)
    plate18 = Canvas(obj, bg='black', height=70, width=70)
    plate18.grid(row=7, column=4)
    plate19 = Canvas(obj, bg='black', height=70, width=70)
    plate19.grid(row=7, column=5)
    plate20 = Canvas(obj, bg='black', height=70, width=70)
    plate20.grid(row=7, column=6)
    plate21 = Canvas(obj, bg='black', height=70, width=70)
    plate21.grid(row=7, column=7)


def color3():
    plate1 = Canvas(obj, bg='black', height=70, width=70)
    plate1.grid(row=3, column=1)
    plate2 = Canvas(obj, bg='black', height=70, width=70)
    plate2.grid(row=3, column=2)
    plate3 = Canvas(obj, bg='pink', height=70, width=70)
    plate3.create_text(38, 35, text="PINK", fill="black", font='Helvetica 10 bold')
    plate3.grid(row=3, column=3)
    plate4 = Canvas(obj, bg='black', height=70, width=70)
    plate4.grid(row=3, column=4)
    plate5 = Canvas(obj, bg='black', height=70, width=70)
    plate5.grid(row=3, column=5)
    plate6 = Canvas(obj, bg='black', height=70, width=70)
    plate6.grid(row=3, column=6)
    plate7 = Canvas(obj, bg='black', height=70, width=70)
    plate7.grid(row=3, column=7)
    plate8 = Canvas(obj, bg='black', height=70, width=70)
    plate8.grid(row=5, column=1)
    plate9 = Canvas(obj, bg='black', height=70, width=70)
    plate9.grid(row=5, column=2)
    plate10 = Canvas(obj, bg='black', height=70, width=70)
    plate10.grid(row=5, column=3)
    plate11 = Canvas(obj, bg='black', height=70, width=70)
    plate11.grid(row=5, column=4)
    plate12 = Canvas(obj, bg='black', height=70, width=70)
    plate12.grid(row=5, column=5)
    plate13 = Canvas(obj, bg='black', height=70, width=70)
    plate13.grid(row=5, column=6)
    plate14 = Canvas(obj, bg='black', height=70, width=70)
    plate14.grid(row=5, column=7)
    plate15 = Canvas(obj, bg='black', height=70, width=70)
    plate15.grid(row=7, column=1)
    plate16 = Canvas(obj, bg='black', height=70, width=70)
    plate16.grid(row=7, column=2)
    plate17 = Canvas(obj, bg='black', height=70, width=70)
    plate17.grid(row=7, column=3)
    plate18 = Canvas(obj, bg='black', height=70, width=70)
    plate18.grid(row=7, column=4)
    plate19 = Canvas(obj, bg='black', height=70, width=70)
    plate19.grid(row=7, column=5)
    plate20 = Canvas(obj, bg='black', height=70, width=70)
    plate20.grid(row=7, column=6)
    plate21 = Canvas(obj, bg='black', height=70, width=70)
    plate21.grid(row=7, column=7)


def color4():
    plate1 = Canvas(obj, bg='black', height=70, width=70)
    plate1.grid(row=3, column=1)
    plate2 = Canvas(obj, bg='black', height=70, width=70)
    plate2.grid(row=3, column=2)
    plate3 = Canvas(obj, bg='black', height=70, width=70)
    plate3.grid(row=3, column=3)
    plate4 = Canvas(obj, bg='orange', height=70, width=70)
    plate4.create_text(38, 35, text="ORANGE", fill="black", font='Helvetica 10 bold')
    plate4.grid(row=3, column=4)
    plate5 = Canvas(obj, bg='black', height=70, width=70)
    plate5.grid(row=3, column=5)
    plate6 = Canvas(obj, bg='black', height=70, width=70)
    plate6.grid(row=3, column=6)
    plate7 = Canvas(obj, bg='black', height=70, width=70)
    plate7.grid(row=3, column=7)
    plate8 = Canvas(obj, bg='black', height=70, width=70)
    plate8.grid(row=5, column=1)
    plate9 = Canvas(obj, bg='black', height=70, width=70)
    plate9.grid(row=5, column=2)
    plate10 = Canvas(obj, bg='black', height=70, width=70)
    plate10.grid(row=5, column=3)
    plate11 = Canvas(obj, bg='black', height=70, width=70)
    plate11.grid(row=5, column=4)
    plate12 = Canvas(obj, bg='black', height=70, width=70)
    plate12.grid(row=5, column=5)
    plate13 = Canvas(obj, bg='black', height=70, width=70)
    plate13.grid(row=5, column=6)
    plate14 = Canvas(obj, bg='black', height=70, width=70)
    plate14.grid(row=5, column=7)
    plate15 = Canvas(obj, bg='black', height=70, width=70)
    plate15.grid(row=7, column=1)
    plate16 = Canvas(obj, bg='black', height=70, width=70)
    plate16.grid(row=7, column=2)
    plate17 = Canvas(obj, bg='black', height=70, width=70)
    plate17.grid(row=7, column=3)
    plate18 = Canvas(obj, bg='black', height=70, width=70)
    plate18.grid(row=7, column=4)
    plate19 = Canvas(obj, bg='black', height=70, width=70)
    plate19.grid(row=7, column=5)
    plate20 = Canvas(obj, bg='black', height=70, width=70)
    plate20.grid(row=7, column=6)
    plate21 = Canvas(obj, bg='black', height=70, width=70)
    plate21.grid(row=7, column=7)


def color5():
    plate1 = Canvas(obj, bg='black', height=70, width=70)
    plate1.grid(row=3, column=1)
    plate2 = Canvas(obj, bg='black', height=70, width=70)
    plate2.grid(row=3, column=2)
    plate3 = Canvas(obj, bg='black', height=70, width=70)
    plate3.grid(row=3, column=3)
    plate4 = Canvas(obj, bg='black', height=70, width=70)
    plate4.grid(row=3, column=4)
    plate5 = Canvas(obj, bg='grey', height=70, width=70)
    plate5.create_text(38, 35, text="GREY", fill="black", font='Helvetica 10 bold')
    plate5.grid(row=3, column=5)
    plate6 = Canvas(obj, bg='black', height=70, width=70)
    plate6.grid(row=3, column=6)
    plate7 = Canvas(obj, bg='black', height=70, width=70)
    plate7.grid(row=3, column=7)
    plate8 = Canvas(obj, bg='black', height=70, width=70)
    plate8.grid(row=5, column=1)
    plate9 = Canvas(obj, bg='black', height=70, width=70)
    plate9.grid(row=5, column=2)
    plate10 = Canvas(obj, bg='black', height=70, width=70)
    plate10.grid(row=5, column=3)
    plate11 = Canvas(obj, bg='black', height=70, width=70)
    plate11.grid(row=5, column=4)
    plate12 = Canvas(obj, bg='black', height=70, width=70)
    plate12.grid(row=5, column=5)
    plate13 = Canvas(obj, bg='black', height=70, width=70)
    plate13.grid(row=5, column=6)
    plate14 = Canvas(obj, bg='black', height=70, width=70)
    plate14.grid(row=5, column=7)
    plate15 = Canvas(obj, bg='black', height=70, width=70)
    plate15.grid(row=7, column=1)
    plate16 = Canvas(obj, bg='black', height=70, width=70)
    plate16.grid(row=7, column=2)
    plate17 = Canvas(obj, bg='black', height=70, width=70)
    plate17.grid(row=7, column=3)
    plate18 = Canvas(obj, bg='black', height=70, width=70)
    plate18.grid(row=7, column=4)
    plate19 = Canvas(obj, bg='black', height=70, width=70)
    plate19.grid(row=7, column=5)
    plate20 = Canvas(obj, bg='black', height=70, width=70)
    plate20.grid(row=7, column=6)
    plate21 = Canvas(obj, bg='black', height=70, width=70)
    plate21.grid(row=7, column=7)


def color6():
    plate1 = Canvas(obj, bg='black', height=70, width=70)
    plate1.grid(row=3, column=1)
    plate2 = Canvas(obj, bg='black', height=70, width=70)
    plate2.grid(row=3, column=2)
    plate3 = Canvas(obj, bg='black', height=70, width=70)
    plate3.grid(row=3, column=3)
    plate4 = Canvas(obj, bg='black', height=70, width=70)
    plate4.grid(row=3, column=4)
    plate5 = Canvas(obj, bg='black', height=70, width=70)
    plate5.grid(row=3, column=5)
    plate6 = Canvas(obj, bg='aqua', height=70, width=70)
    plate6.create_text(38, 35, text="AQUA", fill="black", font='Helvetica 10 bold')
    plate6.grid(row=3, column=6)
    plate7 = Canvas(obj, bg='black', height=70, width=70)
    plate7.grid(row=3, column=7)
    plate8 = Canvas(obj, bg='black', height=70, width=70)
    plate8.grid(row=5, column=1)
    plate9 = Canvas(obj, bg='black', height=70, width=70)
    plate9.grid(row=5, column=2)
    plate10 = Canvas(obj, bg='black', height=70, width=70)
    plate10.grid(row=5, column=3)
    plate11 = Canvas(obj, bg='black', height=70, width=70)
    plate11.grid(row=5, column=4)
    plate12 = Canvas(obj, bg='black', height=70, width=70)
    plate12.grid(row=5, column=5)
    plate13 = Canvas(obj, bg='black', height=70, width=70)
    plate13.grid(row=5, column=6)
    plate14 = Canvas(obj, bg='black', height=70, width=70)
    plate14.grid(row=5, column=7)
    plate15 = Canvas(obj, bg='black', height=70, width=70)
    plate15.grid(row=7, column=1)
    plate16 = Canvas(obj, bg='black', height=70, width=70)
    plate16.grid(row=7, column=2)
    plate17 = Canvas(obj, bg='black', height=70, width=70)
    plate17.grid(row=7, column=3)
    plate18 = Canvas(obj, bg='black', height=70, width=70)
    plate18.grid(row=7, column=4)
    plate19 = Canvas(obj, bg='black', height=70, width=70)
    plate19.grid(row=7, column=5)
    plate20 = Canvas(obj, bg='black', height=70, width=70)
    plate20.grid(row=7, column=6)
    plate21 = Canvas(obj, bg='black', height=70, width=70)
    plate21.grid(row=7, column=7)


def color7():
    plate1 = Canvas(obj, bg='black', height=70, width=70)
    plate1.grid(row=3, column=1)
    plate2 = Canvas(obj, bg='black', height=70, width=70)
    plate2.grid(row=3, column=2)
    plate3 = Canvas(obj, bg='black', height=70, width=70)
    plate3.grid(row=3, column=3)
    plate4 = Canvas(obj, bg='black', height=70, width=70)
    plate4.grid(row=3, column=4)
    plate5 = Canvas(obj, bg='black', height=70, width=70)
    plate5.grid(row=3, column=5)
    plate6 = Canvas(obj, bg='black', height=70, width=70)
    plate6.grid(row=3, column=6)
    plate7 = Canvas(obj, bg='white', height=70, width=70)
    plate7.create_text(38, 35, text="WHITE", fill="black", font='Helvetica 10 bold')
    plate7.grid(row=3, column=7)
    plate8 = Canvas(obj, bg='black', height=70, width=70)
    plate8.grid(row=5, column=1)
    plate9 = Canvas(obj, bg='black', height=70, width=70)
    plate9.grid(row=5, column=2)
    plate10 = Canvas(obj, bg='black', height=70, width=70)
    plate10.grid(row=5, column=3)
    plate11 = Canvas(obj, bg='black', height=70, width=70)
    plate11.grid(row=5, column=4)
    plate12 = Canvas(obj, bg='black', height=70, width=70)
    plate12.grid(row=5, column=5)
    plate13 = Canvas(obj, bg='black', height=70, width=70)
    plate13.grid(row=5, column=6)
    plate14 = Canvas(obj, bg='black', height=70, width=70)
    plate14.grid(row=5, column=7)
    plate15 = Canvas(obj, bg='black', height=70, width=70)
    plate15.grid(row=7, column=1)
    plate16 = Canvas(obj, bg='black', height=70, width=70)
    plate16.grid(row=7, column=2)
    plate17 = Canvas(obj, bg='black', height=70, width=70)
    plate17.grid(row=7, column=3)
    plate18 = Canvas(obj, bg='black', height=70, width=70)
    plate18.grid(row=7, column=4)
    plate19 = Canvas(obj, bg='black', height=70, width=70)
    plate19.grid(row=7, column=5)
    plate20 = Canvas(obj, bg='black', height=70, width=70)
    plate20.grid(row=7, column=6)
    plate21 = Canvas(obj, bg='black', height=70, width=70)
    plate21.grid(row=7, column=7)


def color8():
    plate1 = Canvas(obj, bg='black', height=70, width=70)
    plate1.grid(row=3, column=1)
    plate2 = Canvas(obj, bg='black', height=70, width=70)
    plate2.grid(row=3, column=2)
    plate3 = Canvas(obj, bg='black', height=70, width=70)
    plate3.grid(row=3, column=3)
    plate4 = Canvas(obj, bg='black', height=70, width=70)
    plate4.grid(row=3, column=4)
    plate5 = Canvas(obj, bg='black', height=70, width=70)
    plate5.grid(row=3, column=5)
    plate6 = Canvas(obj, bg='black', height=70, width=70)
    plate6.grid(row=3, column=6)
    plate7 = Canvas(obj, bg='black', height=70, width=70)
    plate7.grid(row=3, column=7)
    plate8 = Canvas(obj, bg='purple', height=70, width=70)
    plate8.create_text(38, 35, text="PURPLE", fill="black", font='Helvetica 10 bold')
    plate8.grid(row=5, column=1)
    plate9 = Canvas(obj, bg='black', height=70, width=70)
    plate9.grid(row=5, column=2)
    plate10 = Canvas(obj, bg='black', height=70, width=70)
    plate10.grid(row=5, column=3)
    plate11 = Canvas(obj, bg='black', height=70, width=70)
    plate11.grid(row=5, column=4)
    plate12 = Canvas(obj, bg='black', height=70, width=70)
    plate12.grid(row=5, column=5)
    plate13 = Canvas(obj, bg='black', height=70, width=70)
    plate13.grid(row=5, column=6)
    plate14 = Canvas(obj, bg='black', height=70, width=70)
    plate14.grid(row=5, column=7)
    plate15 = Canvas(obj, bg='black', height=70, width=70)
    plate15.grid(row=7, column=1)
    plate16 = Canvas(obj, bg='black', height=70, width=70)
    plate16.grid(row=7, column=2)
    plate17 = Canvas(obj, bg='black', height=70, width=70)
    plate17.grid(row=7, column=3)
    plate18 = Canvas(obj, bg='black', height=70, width=70)
    plate18.grid(row=7, column=4)
    plate19 = Canvas(obj, bg='black', height=70, width=70)
    plate19.grid(row=7, column=5)
    plate20 = Canvas(obj, bg='black', height=70, width=70)
    plate20.grid(row=7, column=6)
    plate21 = Canvas(obj, bg='black', height=70, width=70)
    plate21.grid(row=7, column=7)


def color9():
    plate1 = Canvas(obj, bg='black', height=70, width=70)
    plate1.grid(row=3, column=1)
    plate2 = Canvas(obj, bg='black', height=70, width=70)
    plate2.grid(row=3, column=2)
    plate3 = Canvas(obj, bg='black', height=70, width=70)
    plate3.grid(row=3, column=3)
    plate4 = Canvas(obj, bg='black', height=70, width=70)
    plate4.grid(row=3, column=4)
    plate5 = Canvas(obj, bg='black', height=70, width=70)
    plate5.grid(row=3, column=5)
    plate6 = Canvas(obj, bg='black', height=70, width=70)
    plate6.grid(row=3, column=6)
    plate7 = Canvas(obj, bg='black', height=70, width=70)
    plate7.grid(row=3, column=7)
    plate8 = Canvas(obj, bg='black', height=70, width=70)
    plate8.grid(row=5, column=1)
    plate9 = Canvas(obj, bg='Magenta', height=70, width=70)
    plate9.create_text(38, 35, text="MAGENTA", fill="black", font='Helvetica 10 bold')
    plate9.grid(row=5, column=2)
    plate10 = Canvas(obj, bg='black', height=70, width=70)
    plate10.grid(row=5, column=3)
    plate11 = Canvas(obj, bg='black', height=70, width=70)
    plate11.grid(row=5, column=4)
    plate12 = Canvas(obj, bg='black', height=70, width=70)
    plate12.grid(row=5, column=5)
    plate13 = Canvas(obj, bg='black', height=70, width=70)
    plate13.grid(row=5, column=6)
    plate14 = Canvas(obj, bg='black', height=70, width=70)
    plate14.grid(row=5, column=7)
    plate15 = Canvas(obj, bg='black', height=70, width=70)
    plate15.grid(row=7, column=1)
    plate16 = Canvas(obj, bg='black', height=70, width=70)
    plate16.grid(row=7, column=2)
    plate17 = Canvas(obj, bg='black', height=70, width=70)
    plate17.grid(row=7, column=3)
    plate18 = Canvas(obj, bg='black', height=70, width=70)
    plate18.grid(row=7, column=4)
    plate19 = Canvas(obj, bg='black', height=70, width=70)
    plate19.grid(row=7, column=5)
    plate20 = Canvas(obj, bg='black', height=70, width=70)
    plate20.grid(row=7, column=6)
    plate21 = Canvas(obj, bg='black', height=70, width=70)
    plate21.grid(row=7, column=7)


def color10():
    plate1 = Canvas(obj, bg='black', height=70, width=70)
    plate1.grid(row=3, column=1)
    plate2 = Canvas(obj, bg='black', height=70, width=70)
    plate2.grid(row=3, column=2)
    plate3 = Canvas(obj, bg='black', height=70, width=70)
    plate3.grid(row=3, column=3)
    plate4 = Canvas(obj, bg='black', height=70, width=70)
    plate4.grid(row=3, column=4)
    plate5 = Canvas(obj, bg='black', height=70, width=70)
    plate5.grid(row=3, column=5)
    plate6 = Canvas(obj, bg='black', height=70, width=70)
    plate6.grid(row=3, column=6)
    plate7 = Canvas(obj, bg='black', height=70, width=70)
    plate7.grid(row=3, column=7)
    plate8 = Canvas(obj, bg='black', height=70, width=70)
    plate8.grid(row=5, column=1)
    plate9 = Canvas(obj, bg='black', height=70, width=70)
    plate9.grid(row=5, column=2)
    plate10 = Canvas(obj, bg='Cyan', height=70, width=70)
    plate10.create_text(38, 35, text="CYAN", fill="black", font='Helvetica 10 bold')
    plate10.grid(row=5, column=3)
    plate11 = Canvas(obj, bg='black', height=70, width=70)
    plate11.grid(row=5, column=4)
    plate12 = Canvas(obj, bg='black', height=70, width=70)
    plate12.grid(row=5, column=5)
    plate13 = Canvas(obj, bg='black', height=70, width=70)
    plate13.grid(row=5, column=6)
    plate14 = Canvas(obj, bg='black', height=70, width=70)
    plate14.grid(row=5, column=7)
    plate15 = Canvas(obj, bg='black', height=70, width=70)
    plate15.grid(row=7, column=1)
    plate16 = Canvas(obj, bg='black', height=70, width=70)
    plate16.grid(row=7, column=2)
    plate17 = Canvas(obj, bg='black', height=70, width=70)
    plate17.grid(row=7, column=3)
    plate18 = Canvas(obj, bg='black', height=70, width=70)
    plate18.grid(row=7, column=4)
    plate19 = Canvas(obj, bg='black', height=70, width=70)
    plate19.grid(row=7, column=5)
    plate20 = Canvas(obj, bg='black', height=70, width=70)
    plate20.grid(row=7, column=6)
    plate21 = Canvas(obj, bg='black', height=70, width=70)
    plate21.grid(row=7, column=7)


def color11():
    plate1 = Canvas(obj, bg='black', height=70, width=70)
    plate1.grid(row=3, column=1)
    plate2 = Canvas(obj, bg='black', height=70, width=70)
    plate2.grid(row=3, column=2)
    plate3 = Canvas(obj, bg='black', height=70, width=70)
    plate3.grid(row=3, column=3)
    plate4 = Canvas(obj, bg='black', height=70, width=70)
    plate4.grid(row=3, column=4)
    plate5 = Canvas(obj, bg='black', height=70, width=70)
    plate5.grid(row=3, column=5)
    plate6 = Canvas(obj, bg='black', height=70, width=70)
    plate6.grid(row=3, column=6)
    plate7 = Canvas(obj, bg='black', height=70, width=70)
    plate7.grid(row=3, column=7)
    plate8 = Canvas(obj, bg='black', height=70, width=70)
    plate8.grid(row=5, column=1)
    plate9 = Canvas(obj, bg='black', height=70, width=70)
    plate9.grid(row=5, column=2)
    plate10 = Canvas(obj, bg='black', height=70, width=70)
    plate10.grid(row=5, column=3)
    plate11 = Canvas(obj, bg='Gold', height=70, width=70)
    plate11.create_text(38, 35, text="GOLD", fill="black", font='Helvetica 10 bold')
    plate11.grid(row=5, column=4)
    plate12 = Canvas(obj, bg='black', height=70, width=70)
    plate12.grid(row=5, column=5)
    plate13 = Canvas(obj, bg='black', height=70, width=70)
    plate13.grid(row=5, column=6)
    plate14 = Canvas(obj, bg='black', height=70, width=70)
    plate14.grid(row=5, column=7)
    plate15 = Canvas(obj, bg='black', height=70, width=70)
    plate15.grid(row=7, column=1)
    plate16 = Canvas(obj, bg='black', height=70, width=70)
    plate16.grid(row=7, column=2)
    plate17 = Canvas(obj, bg='black', height=70, width=70)
    plate17.grid(row=7, column=3)
    plate18 = Canvas(obj, bg='black', height=70, width=70)
    plate18.grid(row=7, column=4)
    plate19 = Canvas(obj, bg='black', height=70, width=70)
    plate19.grid(row=7, column=5)
    plate20 = Canvas(obj, bg='black', height=70, width=70)
    plate20.grid(row=7, column=6)
    plate21 = Canvas(obj, bg='black', height=70, width=70)
    plate21.grid(row=7, column=7)


def color12():
    plate1 = Canvas(obj, bg='black', height=70, width=70)
    plate1.grid(row=3, column=1)
    plate2 = Canvas(obj, bg='black', height=70, width=70)
    plate2.grid(row=3, column=2)
    plate3 = Canvas(obj, bg='black', height=70, width=70)
    plate3.grid(row=3, column=3)
    plate4 = Canvas(obj, bg='black', height=70, width=70)
    plate4.grid(row=3, column=4)
    plate5 = Canvas(obj, bg='black', height=70, width=70)
    plate5.grid(row=3, column=5)
    plate6 = Canvas(obj, bg='black', height=70, width=70)
    plate6.grid(row=3, column=6)
    plate7 = Canvas(obj, bg='black', height=70, width=70)
    plate7.grid(row=3, column=7)
    plate8 = Canvas(obj, bg='black', height=70, width=70)
    plate8.grid(row=5, column=1)
    plate9 = Canvas(obj, bg='black', height=70, width=70)
    plate9.grid(row=5, column=2)
    plate10 = Canvas(obj, bg='black', height=70, width=70)
    plate10.grid(row=5, column=3)
    plate11 = Canvas(obj, bg='black', height=70, width=70)
    plate11.grid(row=5, column=4)
    plate12 = Canvas(obj, bg='Tan', height=70, width=70)
    plate12.create_text(38, 35, text="TAN", fill="black", font='Helvetica 10 bold')
    plate12.grid(row=5, column=5)
    plate13 = Canvas(obj, bg='black', height=70, width=70)
    plate13.grid(row=5, column=6)
    plate14 = Canvas(obj, bg='black', height=70, width=70)
    plate14.grid(row=5, column=7)
    plate15 = Canvas(obj, bg='black', height=70, width=70)
    plate15.grid(row=7, column=1)
    plate16 = Canvas(obj, bg='black', height=70, width=70)
    plate16.grid(row=7, column=2)
    plate17 = Canvas(obj, bg='black', height=70, width=70)
    plate17.grid(row=7, column=3)
    plate18 = Canvas(obj, bg='black', height=70, width=70)
    plate18.grid(row=7, column=4)
    plate19 = Canvas(obj, bg='black', height=70, width=70)
    plate19.grid(row=7, column=5)
    plate20 = Canvas(obj, bg='black', height=70, width=70)
    plate20.grid(row=7, column=6)
    plate21 = Canvas(obj, bg='black', height=70, width=70)
    plate21.grid(row=7, column=7)


def color13():
    plate1 = Canvas(obj, bg='black', height=70, width=70)
    plate1.grid(row=3, column=1)
    plate2 = Canvas(obj, bg='black', height=70, width=70)
    plate2.grid(row=3, column=2)
    plate3 = Canvas(obj, bg='black', height=70, width=70)
    plate3.grid(row=3, column=3)
    plate4 = Canvas(obj, bg='black', height=70, width=70)
    plate4.grid(row=3, column=4)
    plate5 = Canvas(obj, bg='black', height=70, width=70)
    plate5.grid(row=3, column=5)
    plate6 = Canvas(obj, bg='black', height=70, width=70)
    plate6.grid(row=3, column=6)
    plate7 = Canvas(obj, bg='black', height=70, width=70)
    plate7.grid(row=3, column=7)
    plate8 = Canvas(obj, bg='black', height=70, width=70)
    plate8.grid(row=5, column=1)
    plate9 = Canvas(obj, bg='black', height=70, width=70)
    plate9.grid(row=5, column=2)
    plate10 = Canvas(obj, bg='black', height=70, width=70)
    plate10.grid(row=5, column=3)
    plate11 = Canvas(obj, bg='black', height=70, width=70)
    plate11.grid(row=5, column=4)
    plate12 = Canvas(obj, bg='black', height=70, width=70)
    plate12.grid(row=5, column=5)
    plate13 = Canvas(obj, bg='Navy Blue', height=70, width=70)
    plate13.create_text(38, 35, text="NAVY BLUE", fill="black", font='Helvetica 10 bold')
    plate13.grid(row=5, column=6)
    plate14 = Canvas(obj, bg='black', height=70, width=70)
    plate14.grid(row=5, column=7)
    plate15 = Canvas(obj, bg='black', height=70, width=70)
    plate15.grid(row=7, column=1)
    plate16 = Canvas(obj, bg='black', height=70, width=70)
    plate16.grid(row=7, column=2)
    plate17 = Canvas(obj, bg='black', height=70, width=70)
    plate17.grid(row=7, column=3)
    plate18 = Canvas(obj, bg='black', height=70, width=70)
    plate18.grid(row=7, column=4)
    plate19 = Canvas(obj, bg='black', height=70, width=70)
    plate19.grid(row=7, column=5)
    plate20 = Canvas(obj, bg='black', height=70, width=70)
    plate20.grid(row=7, column=6)
    plate21 = Canvas(obj, bg='black', height=70, width=70)
    plate21.grid(row=7, column=7)


def color14():
    plate1 = Canvas(obj, bg='black', height=70, width=70)
    plate1.grid(row=3, column=1)
    plate2 = Canvas(obj, bg='black', height=70, width=70)
    plate2.grid(row=3, column=2)
    plate3 = Canvas(obj, bg='black', height=70, width=70)
    plate3.grid(row=3, column=3)
    plate4 = Canvas(obj, bg='black', height=70, width=70)
    plate4.grid(row=3, column=4)
    plate5 = Canvas(obj, bg='black', height=70, width=70)
    plate5.grid(row=3, column=5)
    plate6 = Canvas(obj, bg='black', height=70, width=70)
    plate6.grid(row=3, column=6)
    plate7 = Canvas(obj, bg='black', height=70, width=70)
    plate7.grid(row=3, column=7)
    plate8 = Canvas(obj, bg='black', height=70, width=70)
    plate8.grid(row=5, column=1)
    plate9 = Canvas(obj, bg='black', height=70, width=70)
    plate9.grid(row=5, column=2)
    plate10 = Canvas(obj, bg='black', height=70, width=70)
    plate10.grid(row=5, column=3)
    plate11 = Canvas(obj, bg='black', height=70, width=70)
    plate11.grid(row=5, column=4)
    plate12 = Canvas(obj, bg='black', height=70, width=70)
    plate12.grid(row=5, column=5)
    plate13 = Canvas(obj, bg='black', height=70, width=70)
    plate13.grid(row=5, column=6)
    plate14 = Canvas(obj, bg='Indigo', height=70, width=70)
    plate14.create_text(38, 35, text="INDIGO", fill="black", font='Helvetica 10 bold')
    plate14.grid(row=5, column=7)
    plate15 = Canvas(obj, bg='black', height=70, width=70)
    plate15.grid(row=7, column=1)
    plate16 = Canvas(obj, bg='black', height=70, width=70)
    plate16.grid(row=7, column=2)
    plate17 = Canvas(obj, bg='black', height=70, width=70)
    plate17.grid(row=7, column=3)
    plate18 = Canvas(obj, bg='black', height=70, width=70)
    plate18.grid(row=7, column=4)
    plate19 = Canvas(obj, bg='black', height=70, width=70)
    plate19.grid(row=7, column=5)
    plate20 = Canvas(obj, bg='black', height=70, width=70)
    plate20.grid(row=7, column=6)
    plate21 = Canvas(obj, bg='black', height=70, width=70)
    plate21.grid(row=7, column=7)


def color15():
    plate1 = Canvas(obj, bg='black', height=70, width=70)
    plate1.grid(row=3, column=1)
    plate2 = Canvas(obj, bg='black', height=70, width=70)
    plate2.grid(row=3, column=2)
    plate3 = Canvas(obj, bg='black', height=70, width=70)
    plate3.grid(row=3, column=3)
    plate4 = Canvas(obj, bg='black', height=70, width=70)
    plate4.grid(row=3, column=4)
    plate5 = Canvas(obj, bg='black', height=70, width=70)
    plate5.grid(row=3, column=5)
    plate6 = Canvas(obj, bg='black', height=70, width=70)
    plate6.grid(row=3, column=6)
    plate7 = Canvas(obj, bg='black', height=70, width=70)
    plate7.grid(row=3, column=7)
    plate8 = Canvas(obj, bg='black', height=70, width=70)
    plate8.grid(row=5, column=1)
    plate9 = Canvas(obj, bg='black', height=70, width=70)
    plate9.grid(row=5, column=2)
    plate10 = Canvas(obj, bg='black', height=70, width=70)
    plate10.grid(row=5, column=3)
    plate11 = Canvas(obj, bg='black', height=70, width=70)
    plate11.grid(row=5, column=4)
    plate12 = Canvas(obj, bg='black', height=70, width=70)
    plate12.grid(row=5, column=5)
    plate13 = Canvas(obj, bg='black', height=70, width=70)
    plate13.grid(row=5, column=6)
    plate14 = Canvas(obj, bg='black', height=70, width=70)
    plate14.grid(row=5, column=7)
    plate15 = Canvas(obj, bg='Violet', height=70, width=70)
    plate15.create_text(38, 35, text="VIOLET", fill="black", font='Helvetica 10 bold')
    plate15.grid(row=7, column=1)
    plate16 = Canvas(obj, bg='black', height=70, width=70)
    plate16.grid(row=7, column=2)
    plate17 = Canvas(obj, bg='black', height=70, width=70)
    plate17.grid(row=7, column=3)
    plate18 = Canvas(obj, bg='black', height=70, width=70)
    plate18.grid(row=7, column=4)
    plate19 = Canvas(obj, bg='black', height=70, width=70)
    plate19.grid(row=7, column=5)
    plate20 = Canvas(obj, bg='black', height=70, width=70)
    plate20.grid(row=7, column=6)
    plate21 = Canvas(obj, bg='black', height=70, width=70)
    plate21.grid(row=7, column=7)


def color16():
    plate1 = Canvas(obj, bg='black', height=70, width=70)
    plate1.grid(row=3, column=1)
    plate2 = Canvas(obj, bg='black', height=70, width=70)
    plate2.grid(row=3, column=2)
    plate3 = Canvas(obj, bg='black', height=70, width=70)
    plate3.grid(row=3, column=3)
    plate4 = Canvas(obj, bg='black', height=70, width=70)
    plate4.grid(row=3, column=4)
    plate5 = Canvas(obj, bg='black', height=70, width=70)
    plate5.grid(row=3, column=5)
    plate6 = Canvas(obj, bg='black', height=70, width=70)
    plate6.grid(row=3, column=6)
    plate7 = Canvas(obj, bg='black', height=70, width=70)
    plate7.grid(row=3, column=7)
    plate8 = Canvas(obj, bg='black', height=70, width=70)
    plate8.grid(row=5, column=1)
    plate9 = Canvas(obj, bg='black', height=70, width=70)
    plate9.grid(row=5, column=2)
    plate10 = Canvas(obj, bg='black', height=70, width=70)
    plate10.grid(row=5, column=3)
    plate11 = Canvas(obj, bg='black', height=70, width=70)
    plate11.grid(row=5, column=4)
    plate12 = Canvas(obj, bg='black', height=70, width=70)
    plate12.grid(row=5, column=5)
    plate13 = Canvas(obj, bg='black', height=70, width=70)
    plate13.grid(row=5, column=6)
    plate14 = Canvas(obj, bg='black', height=70, width=70)
    plate14.grid(row=5, column=7)
    plate15 = Canvas(obj, bg='black', height=70, width=70)
    plate15.grid(row=7, column=1)
    plate16 = Canvas(obj, bg='Maroon', height=70, width=70)
    plate16.create_text(38, 35, text="MAROON", fill="black", font='Helvetica 10 bold')
    plate16.grid(row=7, column=2)
    plate17 = Canvas(obj, bg='black', height=70, width=70)
    plate17.grid(row=7, column=3)
    plate18 = Canvas(obj, bg='black', height=70, width=70)
    plate18.grid(row=7, column=4)
    plate19 = Canvas(obj, bg='black', height=70, width=70)
    plate19.grid(row=7, column=5)
    plate20 = Canvas(obj, bg='black', height=70, width=70)
    plate20.grid(row=7, column=6)
    plate21 = Canvas(obj, bg='black', height=70, width=70)
    plate21.grid(row=7, column=7)


def color17():
    plate1 = Canvas(obj, bg='black', height=70, width=70)
    plate1.grid(row=3, column=1)
    plate2 = Canvas(obj, bg='black', height=70, width=70)
    plate2.grid(row=3, column=2)
    plate3 = Canvas(obj, bg='black', height=70, width=70)
    plate3.grid(row=3, column=3)
    plate4 = Canvas(obj, bg='black', height=70, width=70)
    plate4.grid(row=3, column=4)
    plate5 = Canvas(obj, bg='black', height=70, width=70)
    plate5.grid(row=3, column=5)
    plate6 = Canvas(obj, bg='black', height=70, width=70)
    plate6.grid(row=3, column=6)
    plate7 = Canvas(obj, bg='black', height=70, width=70)
    plate7.grid(row=3, column=7)
    plate8 = Canvas(obj, bg='black', height=70, width=70)
    plate8.grid(row=5, column=1)
    plate9 = Canvas(obj, bg='black', height=70, width=70)
    plate9.grid(row=5, column=2)
    plate10 = Canvas(obj, bg='black', height=70, width=70)
    plate10.grid(row=5, column=3)
    plate11 = Canvas(obj, bg='black', height=70, width=70)
    plate11.grid(row=5, column=4)
    plate12 = Canvas(obj, bg='black', height=70, width=70)
    plate12.grid(row=5, column=5)
    plate13 = Canvas(obj, bg='black', height=70, width=70)
    plate13.grid(row=5, column=6)
    plate14 = Canvas(obj, bg='black', height=70, width=70)
    plate14.grid(row=5, column=7)
    plate15 = Canvas(obj, bg='black', height=70, width=70)
    plate15.grid(row=7, column=1)
    plate16 = Canvas(obj, bg='black', height=70, width=70)
    plate16.grid(row=7, column=2)
    plate17 = Canvas(obj, bg='Olive', height=70, width=70)
    plate17.create_text(38, 35, text="OLIVE", fill="black", font='Helvetica 10 bold')
    plate17.grid(row=7, column=3)
    plate18 = Canvas(obj, bg='black', height=70, width=70)
    plate18.grid(row=7, column=4)
    plate19 = Canvas(obj, bg='black', height=70, width=70)
    plate19.grid(row=7, column=5)
    plate20 = Canvas(obj, bg='black', height=70, width=70)
    plate20.grid(row=7, column=6)
    plate21 = Canvas(obj, bg='black', height=70, width=70)
    plate21.grid(row=7, column=7)


def color18():
    plate1 = Canvas(obj, bg='black', height=70, width=70)
    plate1.grid(row=3, column=1)
    plate2 = Canvas(obj, bg='black', height=70, width=70)
    plate2.grid(row=3, column=2)
    plate3 = Canvas(obj, bg='black', height=70, width=70)
    plate3.grid(row=3, column=3)
    plate4 = Canvas(obj, bg='black', height=70, width=70)
    plate4.grid(row=3, column=4)
    plate5 = Canvas(obj, bg='black', height=70, width=70)
    plate5.grid(row=3, column=5)
    plate6 = Canvas(obj, bg='black', height=70, width=70)
    plate6.grid(row=3, column=6)
    plate7 = Canvas(obj, bg='black', height=70, width=70)
    plate7.grid(row=3, column=7)
    plate8 = Canvas(obj, bg='black', height=70, width=70)
    plate8.grid(row=5, column=1)
    plate9 = Canvas(obj, bg='black', height=70, width=70)
    plate9.grid(row=5, column=2)
    plate10 = Canvas(obj, bg='black', height=70, width=70)
    plate10.grid(row=5, column=3)
    plate11 = Canvas(obj, bg='black', height=70, width=70)
    plate11.grid(row=5, column=4)
    plate12 = Canvas(obj, bg='black', height=70, width=70)
    plate12.grid(row=5, column=5)
    plate13 = Canvas(obj, bg='black', height=70, width=70)
    plate13.grid(row=5, column=6)
    plate14 = Canvas(obj, bg='black', height=70, width=70)
    plate14.grid(row=5, column=7)
    plate15 = Canvas(obj, bg='black', height=70, width=70)
    plate15.grid(row=7, column=1)
    plate16 = Canvas(obj, bg='black', height=70, width=70)
    plate16.grid(row=7, column=2)
    plate17 = Canvas(obj, bg='black', height=70, width=70)
    plate17.grid(row=7, column=3)
    plate18 = Canvas(obj, bg='Brown', height=70, width=70)
    plate18.create_text(38, 35, text="BROWN", fill="black", font='Helvetica 10 bold')
    plate18.grid(row=7, column=4)
    plate19 = Canvas(obj, bg='black', height=70, width=70)
    plate19.grid(row=7, column=5)
    plate20 = Canvas(obj, bg='black', height=70, width=70)
    plate20.grid(row=7, column=6)
    plate21 = Canvas(obj, bg='black', height=70, width=70)
    plate21.grid(row=7, column=7)


def color19():
    plate1 = Canvas(obj, bg='black', height=70, width=70)
    plate1.grid(row=3, column=1)
    plate2 = Canvas(obj, bg='black', height=70, width=70)
    plate2.grid(row=3, column=2)
    plate3 = Canvas(obj, bg='black', height=70, width=70)
    plate3.grid(row=3, column=3)
    plate4 = Canvas(obj, bg='black', height=70, width=70)
    plate4.grid(row=3, column=4)
    plate5 = Canvas(obj, bg='black', height=70, width=70)
    plate5.grid(row=3, column=5)
    plate6 = Canvas(obj, bg='black', height=70, width=70)
    plate6.grid(row=3, column=6)
    plate7 = Canvas(obj, bg='black', height=70, width=70)
    plate7.grid(row=3, column=7)
    plate8 = Canvas(obj, bg='black', height=70, width=70)
    plate8.grid(row=5, column=1)
    plate9 = Canvas(obj, bg='black', height=70, width=70)
    plate9.grid(row=5, column=2)
    plate10 = Canvas(obj, bg='black', height=70, width=70)
    plate10.grid(row=5, column=3)
    plate11 = Canvas(obj, bg='black', height=70, width=70)
    plate11.grid(row=5, column=4)
    plate12 = Canvas(obj, bg='black', height=70, width=70)
    plate12.grid(row=5, column=5)
    plate13 = Canvas(obj, bg='black', height=70, width=70)
    plate13.grid(row=5, column=6)
    plate14 = Canvas(obj, bg='black', height=70, width=70)
    plate14.grid(row=5, column=7)
    plate15 = Canvas(obj, bg='black', height=70, width=70)
    plate15.grid(row=7, column=1)
    plate16 = Canvas(obj, bg='black', height=70, width=70)
    plate16.grid(row=7, column=2)
    plate17 = Canvas(obj, bg='black', height=70, width=70)
    plate17.grid(row=7, column=3)
    plate18 = Canvas(obj, bg='black', height=70, width=70)
    plate18.grid(row=7, column=4)
    plate19 = Canvas(obj, bg='Purple', height=70, width=70)
    plate19.create_text(38, 35, text="PURPLE", fill="black", font='Helvetica 10 bold')
    plate19.grid(row=7, column=5)
    plate20 = Canvas(obj, bg='black', height=70, width=70)
    plate20.grid(row=7, column=6)
    plate21 = Canvas(obj, bg='black', height=70, width=70)
    plate21.grid(row=7, column=7)


def color20():
    plate1 = Canvas(obj, bg='black', height=70, width=70)
    plate1.grid(row=3, column=1)
    plate2 = Canvas(obj, bg='black', height=70, width=70)
    plate2.grid(row=3, column=2)
    plate3 = Canvas(obj, bg='black', height=70, width=70)
    plate3.grid(row=3, column=3)
    plate4 = Canvas(obj, bg='black', height=70, width=70)
    plate4.grid(row=3, column=4)
    plate5 = Canvas(obj, bg='black', height=70, width=70)
    plate5.grid(row=3, column=5)
    plate6 = Canvas(obj, bg='black', height=70, width=70)
    plate6.grid(row=3, column=6)
    plate7 = Canvas(obj, bg='black', height=70, width=70)
    plate7.grid(row=3, column=7)
    plate8 = Canvas(obj, bg='black', height=70, width=70)
    plate8.grid(row=5, column=1)
    plate9 = Canvas(obj, bg='black', height=70, width=70)
    plate9.grid(row=5, column=2)
    plate10 = Canvas(obj, bg='black', height=70, width=70)
    plate10.grid(row=5, column=3)
    plate11 = Canvas(obj, bg='black', height=70, width=70)
    plate11.grid(row=5, column=4)
    plate12 = Canvas(obj, bg='black', height=70, width=70)
    plate12.grid(row=5, column=5)
    plate13 = Canvas(obj, bg='black', height=70, width=70)
    plate13.grid(row=5, column=6)
    plate14 = Canvas(obj, bg='black', height=70, width=70)
    plate14.grid(row=5, column=7)
    plate15 = Canvas(obj, bg='black', height=70, width=70)
    plate15.grid(row=7, column=1)
    plate16 = Canvas(obj, bg='black', height=70, width=70)
    plate16.grid(row=7, column=2)
    plate17 = Canvas(obj, bg='black', height=70, width=70)
    plate17.grid(row=7, column=3)
    plate18 = Canvas(obj, bg='black', height=70, width=70)
    plate18.grid(row=7, column=4)
    plate19 = Canvas(obj, bg='black', height=70, width=70)
    plate19.grid(row=7, column=5)
    plate20 = Canvas(obj, bg='Yellow', height=70, width=70)
    plate20.create_text(38, 35, text="YELLOW", fill="black", font='Helvetica 10 bold')
    plate20.grid(row=7, column=6)
    plate21 = Canvas(obj, bg='black', height=70, width=70)
    plate21.grid(row=7, column=7)


def color21():
    plate1 = Canvas(obj, bg='black', height=70, width=70)
    plate1.grid(row=3, column=1)
    plate2 = Canvas(obj, bg='black', height=70, width=70)
    plate2.grid(row=3, column=2)
    plate3 = Canvas(obj, bg='black', height=70, width=70)
    plate3.grid(row=3, column=3)
    plate4 = Canvas(obj, bg='black', height=70, width=70)
    plate4.grid(row=3, column=4)
    plate5 = Canvas(obj, bg='black', height=70, width=70)
    plate5.grid(row=3, column=5)
    plate6 = Canvas(obj, bg='black', height=70, width=70)
    plate6.grid(row=3, column=6)
    plate7 = Canvas(obj, bg='black', height=70, width=70)
    plate7.grid(row=3, column=7)
    plate8 = Canvas(obj, bg='black', height=70, width=70)
    plate8.grid(row=5, column=1)
    plate9 = Canvas(obj, bg='black', height=70, width=70)
    plate9.grid(row=5, column=2)
    plate10 = Canvas(obj, bg='black', height=70, width=70)
    plate10.grid(row=5, column=3)
    plate11 = Canvas(obj, bg='black', height=70, width=70)
    plate11.grid(row=5, column=4)
    plate12 = Canvas(obj, bg='black', height=70, width=70)
    plate12.grid(row=5, column=5)
    plate13 = Canvas(obj, bg='black', height=70, width=70)
    plate13.grid(row=5, column=6)
    plate14 = Canvas(obj, bg='black', height=70, width=70)
    plate14.grid(row=5, column=7)
    plate15 = Canvas(obj, bg='black', height=70, width=70)
    plate15.grid(row=7, column=1)
    plate16 = Canvas(obj, bg='black', height=70, width=70)
    plate16.grid(row=7, column=2)
    plate17 = Canvas(obj, bg='black', height=70, width=70)
    plate17.grid(row=7, column=3)
    plate18 = Canvas(obj, bg='black', height=70, width=70)
    plate18.grid(row=7, column=4)
    plate19 = Canvas(obj, bg='black', height=70, width=70)
    plate19.grid(row=7, column=5)
    plate20 = Canvas(obj, bg='black', height=70, width=70)
    plate20.grid(row=7, column=6)
    plate21 = Canvas(obj, bg='Green', height=70, width=70)
    plate21.create_text(38, 35, text="GREEN", fill="black", font='Helvetica 10 bold')
    plate21.grid(row=7, column=7)


Label(obj, text=' ', bg='black', fg='white', font='a 10 bold').grid(row=1, columnspan=8)
Label(obj, text='Welcome', bg='black', fg='white', font='a 20 bold', justify='center', anchor='center').grid(row=2,
                                                                                                             column=4)

plate1 = Canvas(obj, bg='black', height=70, width=70)
plate1.grid(row=3, column=1)

plate2 = Canvas(obj, bg='black', height=70, width=70)
plate2.grid(row=3, column=2)

plate3 = Canvas(obj, bg='black', height=70, width=70)
plate3.grid(row=3, column=3)

plate4 = Canvas(obj, bg='black', height=70, width=70)
plate4.grid(row=3, column=4)

plate5 = Canvas(obj, bg='black', height=70, width=70)
plate5.grid(row=3, column=5)

plate6 = Canvas(obj, bg='black', height=70, width=70)
plate6.grid(row=3, column=6)

plate7 = Canvas(obj, bg='black', height=70, width=70)
plate7.grid(row=3, column=7)

plate8 = Canvas(obj, bg='black', height=70, width=70)
plate8.grid(row=5, column=1)

plate9 = Canvas(obj, bg='black', height=70, width=70)
plate9.grid(row=5, column=2)

plate10 = Canvas(obj, bg='black', height=70, width=70)
plate10.grid(row=5, column=3)

plate11 = Canvas(obj, bg='black', height=70, width=70)
plate11.grid(row=5, column=4)

plate12 = Canvas(obj, bg='black', height=70, width=70)
plate12.grid(row=5, column=5)

plate13 = Canvas(obj, bg='black', height=70, width=70)
plate13.grid(row=5, column=6)

plate14 = Canvas(obj, bg='black', height=70, width=70)
plate14.grid(row=5, column=7)

plate15 = Canvas(obj, bg='black', height=70, width=70)
plate15.grid(row=7, column=1)

plate16 = Canvas(obj, bg='black', height=70, width=70)
plate16.grid(row=7, column=2)

plate17 = Canvas(obj, bg='black', height=70, width=70)
plate17.grid(row=7, column=3)

plate18 = Canvas(obj, bg='black', height=70, width=70)
plate18.grid(row=7, column=4)

plate19 = Canvas(obj, bg='black', height=70, width=70)
plate19.grid(row=7, column=5)

plate20 = Canvas(obj, bg='black', height=70, width=70)
plate20.grid(row=7, column=6)

plate21 = Canvas(obj, bg='black', height=70, width=70)
plate21.grid(row=7, column=7)
Label(obj, text=' ', bg='black', fg='white', font='a 10 bold').grid(row=8, columnspan=8)
btn21 = Button(obj, command=click, background='grey', height=2, width=10, text='START', fg='black',
               font=('aa 12 bold'))

btn21.grid(row=9, column=4)

Label(obj, text=' ', bg='black', fg='white', font='a 10 bold').grid(row=10, columnspan=8)
Label(obj, text='Developed by RAHUL R  SISPLINT : 329191896', bg='black', fg='white', font='a 10 bold').grid(row=11,
                                                                                                             columnspan=8)
Label(obj, text='DEVELOPER TRAINEE - INTERN', bg='black', fg='white', font='a 10 bold').grid(row=12,
                                                                                             columnspan=8)
obj.mainloop()
